export const SET_X_SESSION_ID = "SET_X_SESSION_ID";
export const SESSION_CLOSED = "SESSION_CLOSED";
export const SESSION_CANCELLED = "SESSION_CANCELLED";
export const SESSION_REFRESH_STARTED = "SESSION_REFRESH_STARTED";
export const SESSION_REFRESH_SUCCESS = "SESSION_REFRESH_SUCCESS";
export const SESSION_REFRESH_ERROR = "SESSION_REFRESH_ERROR";
